### ISSUE TITLE
How to uninstall it

### ISSUE THREAD

**Issue by sergeevabc** [schierlm/IsoMounter#1]
Dear Michael,
What’s the proper way to un-install this app?
I see no relevant shortcut or something like that.

**Comment by schierlm** [comment]
As the app does not store any data persistently, uninstallation is the reverse of installation.

For installation, you extract the EXE to some place on your disk (or your PE image template), to uninstall, just remove the EXE file again.

In case you already mounted some ISOs, you may have to reboot before deleting the EXE file.
